server:
  port: 8089
  tomcat:
    max-swallow-size: 100MB
    max-http-form-post-size: 100MB
    connection-timeout: 60000
    keep-alive-timeout: 60000

  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 2MB

  application:
    name: "FileHub"
    version: 1.0.0

  datasource:
    url: jdbc:h2:./db/java-share-hub;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: devskjj@gmail.com
    password: kfcb dcno zsbi iipr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true

  output:
    ansi:
      enabled: always

  security:
    user:
      name: email
      password: password

  freemarker:
    expose-session-attributes: true
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    root: info
    org:
      springframework:
        security: debug

  file:
    path: log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7